apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-briangreen-io-tls
  namespace: glance
spec:
  secretName: glance-briangreen-io-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - glance.briangreen.io