apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
    - name: Home
      columns:
        - size: small
          widgets:
            - type: calendar
              first-day-of-week: monday

            - type: rss
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://selfh.st/rss/
                  title: selfh.st
                  limit: 4
                - url: https://ciechanow.ski/atom.xml
                - url: https://www.joshwcomeau.com/rss.xml
                  title: Josh Comeau
                - url: https://samwho.dev/rss.xml
                - url: https://ishadeed.com/feed.xml
                  title: Ahmad Shadeed

            - type: twitch-channels
              channels:
                - theprimeagen
                - j_blow
                - piratesoftware
                - cohhcarnage
                - christitustech
                - EJ_SA

        - size: full
          widgets:
            - type: group
              widgets:
                - type: hacker-news
                - type: lobsters

            - type: videos
              channels:
                - UC9N0DmacOi4iWKQyygX89OQ # FightinCowboy
                - UCUUTdohVElFLSP4NBnlPEwA # Jim's Garage
                - UCVS0xBpOtXBAl12rdG67-OQ # Monster Hunter
                - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                - UCsBjURrPoezykLs9EqgamOA # Fireship
                - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

            - type: group
              widgets:
                - type: reddit
                  subreddit: technology
                  show-thumbnails: true
                - type: reddit
                  subreddit: selfhosted
                  show-thumbnails: true

        - size: small
          widgets:
            - type: weather
              location: London, United Kingdom
              units: metric # alternatively "imperial"
              hour-format: 12h # alternatively "24h"
              # Optionally hide the location from being displayed in the widget
              # hide-location: true

            - type: markets
              markets:
                - symbol: SPY
                  name: S&P 500
                - symbol: BTC-USD
                  name: Bitcoin
                - symbol: NVDA
                  name: NVIDIA
                - symbol: AAPL
                  name: Apple
                - symbol: MSFT
                  name: Microsoft

            - type: releases
              cache: 1d
              # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              # read-only token from your Github account settings and use it here to increase the limit.
              # token: ...
              repositories:
                - glanceapp/glance
                - go-gitea/gitea
                - immich-app/immich
                - syncthing/syncthing

    - name: Gaming
      columns:
        - size: small
          widgets:
            - type: twitch-top-games
              limit: 20
              collapse-after: 13
              exclude:
                - just-chatting
                - pools-hot-tubs-and-beaches
                - music
                - art
                - asmr

        - size: full
          widgets:
            - type: group
              widgets:
                - type: reddit
                  show-thumbnails: true
                  subreddit: pcgaming
                - type: reddit
                  subreddit: games

            - type: videos
              style: grid-cards
              collapse-after-rows: 3
              channels:
                - UCNvzD7Z-g64bPXxGzaQaa4g # gameranx
                - UCZ7AeeVbyslLM_8-nVy2B8Q # Skill Up
                - UCHDxYLv8iovIbhrfl16CNyg # GameLinked
                - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry

        - size: small
          widgets:
            - type: reddit
              subreddit: gamingnews
              limit: 7
              style: vertical-cards
