apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-briangreen-io-tls
  namespace: mealie
spec:
  secretName: mealie-briangreen-io-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - mealie.briangreen.io